/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as ApiPublicHooksRefreshCatalogRouteImport } from './routes/api/public/hooks/refresh-catalog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshCatalogRoute =
  ApiPublicHooksRefreshCatalogRouteImport.update({
    id: '/api/public/hooks/refresh-catalog',
    path: '/api/public/hooks/refresh-catalog',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/metrics': typeof MetricsRoute
  '/mood': typeof MoodRoute
  '/recommendations': typeof RecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/public/hooks/refresh-catalog': typeof ApiPublicHooksRefreshCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/metrics': typeof MetricsRoute
  '/mood': typeof MoodRoute
  '/recommendations': typeof RecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/public/hooks/refresh-catalog': typeof ApiPublicHooksRefreshCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/auth': typeof AuthRoute
  '/metrics': typeof MetricsRoute
  '/mood': typeof MoodRoute
  '/recommendations': typeof RecommendationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/public/hooks/refresh-catalog': typeof ApiPublicHooksRefreshCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/auth'
    | '/metrics'
    | '/mood'
    | '/recommendations'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/watchlist'
    | '/movie/$id'
    | '/api/public/hooks/refresh-catalog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/auth'
    | '/metrics'
    | '/mood'
    | '/recommendations'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/watchlist'
    | '/movie/$id'
    | '/api/public/hooks/refresh-catalog'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/auth'
    | '/metrics'
    | '/mood'
    | '/recommendations'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/watchlist'
    | '/movie/$id'
    | '/api/public/hooks/refresh-catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AuthRoute: typeof AuthRoute
  MetricsRoute: typeof MetricsRoute
  MoodRoute: typeof MoodRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchlistRoute: typeof WatchlistRoute
  MovieIdRoute: typeof MovieIdRoute
  ApiPublicHooksRefreshCatalogRoute: typeof ApiPublicHooksRefreshCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-catalog': {
      id: '/api/public/hooks/refresh-catalog'
      path: '/api/public/hooks/refresh-catalog'
      fullPath: '/api/public/hooks/refresh-catalog'
      preLoaderRoute: typeof ApiPublicHooksRefreshCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AuthRoute: AuthRoute,
  MetricsRoute: MetricsRoute,
  MoodRoute: MoodRoute,
  RecommendationsRoute: RecommendationsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchlistRoute: WatchlistRoute,
  MovieIdRoute: MovieIdRoute,
  ApiPublicHooksRefreshCatalogRoute: ApiPublicHooksRefreshCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
